spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
  datasource:
    url: jdbc:mariadb://127.0.0.1/ecomm?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: never
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:/db/migration,/db/seed
  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
        cache: TRACE
