spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: ecomm
  datasource:
    url: jdbc:h2:mem:ecomm;MODE=MySQL
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    schemas: ecomm
    user: sa
  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
        cache: TRACE
