version: "3.8"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecomm
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    platform: linux/amd64